# Generated by Django 6.1 on 2026-06-26 13:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('notification_type', models.CharField(choices=[('OVERDUE_INVOICE', 'Overdue Invoice'), ('DUPLICATE_PAYMENT', 'Duplicate Payment'), ('LARGE_TRANSACTION', 'Large Transaction'), ('CONTROL_VIOLATION', 'Control Violation'), ('LOW_INVENTORY', 'Low Inventory'), ('RECONCILIATION_COMPLETED', 'Reconciliation Completed'), ('SYSTEM', 'System Alert')], db_index=True, default='SYSTEM', max_length=50)),
                ('is_read', models.BooleanField(db_index=True, default=False)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
