# Generated by Django 6.1 on 2026-06-14 11:20

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('vendor', models.CharField(db_index=True, max_length=200)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('date', models.DateField(db_index=True, default=datetime.date.today)),
                ('category', models.CharField(choices=[('TRAVEL', 'Travel & Entertainment'), ('SOFTWARE', 'Software & Cloud Services'), ('LOGISTICS', 'Logistics & Shipping'), ('OFFICE', 'Office & Facilities'), ('INVENTORY', 'Inventory Procurement'), ('SALARY', 'Payroll & Contractor Fees'), ('OTHER', 'Other Operational Expenses')], db_index=True, default='OFFICE', max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('payment_method', models.CharField(default='Corporate Card', max_length=100)),
                ('receipt_doc', models.FileField(blank=True, null=True, upload_to='expenses/receipts/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recorded_expenses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date', '-id'],
            },
        ),
    ]
