# Generated by Django 6.1 on 2026-07-09 18:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Acme Global Corporation', max_length=200)),
                ('slug', models.SlugField(default='acme-corp', max_length=200, unique=True)),
                ('country', models.CharField(default='India', max_length=100)),
                ('currency', models.CharField(default='INR', max_length=10)),
                ('tax_id', models.CharField(blank=True, default='GSTIN27AABCU9603R1ZM', max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='members', to='accounts.organization'),
        ),
    ]
