# Generated by Django 6.1 on 2026-06-26 13:10

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ControlRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('rule_type', models.CharField(choices=[('HIGH_PAYMENT', 'Payment Threshold Violation (> ₹100k)'), ('DUPLICATE_TRANSACTION', 'Duplicate Transaction / Payment Flag'), ('AMOUNT_MISMATCH', 'Invoice vs Bank Amount Mismatch'), ('OVERDUE_INVOICE', 'Critical Overdue Invoice Alert'), ('UNMATCHED_NO_INVOICE', 'Unmatched Bank Transaction without Invoice')], db_index=True, max_length=50, unique=True)),
                ('description', models.TextField()),
                ('severity', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], default='HIGH', max_length=20)),
                ('threshold_amount', models.DecimalField(decimal_places=2, default=Decimal('100000.00'), max_digits=15)),
                ('is_enabled', models.BooleanField(db_index=True, default=True)),
                ('requires_admin_approval', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='ControlViolation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('severity', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], db_index=True, default='HIGH', max_length=20)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('INVESTIGATING', 'Investigating'), ('RESOLVED', 'Resolved'), ('IGNORED', 'Ignored / False Positive')], db_index=True, default='OPEN', max_length=30)),
                ('related_entity_type', models.CharField(blank=True, max_length=100, null=True)),
                ('related_entity_id', models.CharField(blank=True, max_length=100, null=True)),
                ('resolution_notes', models.TextField(blank=True, null=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('assigned_reviewer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_violations', to=settings.AUTH_USER_MODEL)),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_violations', to=settings.AUTH_USER_MODEL)),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='violations', to='controls.controlrule')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
