# Generated by Django 6.1 on 2026-06-08 14:32

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BankTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('description', models.CharField(max_length=255)),
                ('reference', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('is_reconciled', models.BooleanField(db_index=True, default=False)),
                ('cents_key', models.IntegerField(db_index=True, default=0)),
            ],
            options={
                'ordering': ['date', 'id'],
            },
        ),
        migrations.CreateModel(
            name='CompanyTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('account', models.CharField(default='1010 Cash — Operating', max_length=150)),
                ('memo', models.CharField(max_length=255)),
                ('doc_no', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('is_reconciled', models.BooleanField(db_index=True, default=False)),
                ('cents_key', models.IntegerField(db_index=True, default=0)),
            ],
            options={
                'ordering': ['date', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ReconciliationBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('period', models.CharField(default='June 2026', max_length=100)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], db_index=True, default='PENDING', max_length=20)),
                ('bank_file', models.FileField(blank=True, null=True, upload_to='reconciliation/bank_files/')),
                ('gl_file', models.FileField(blank=True, null=True, upload_to='reconciliation/gl_files/')),
                ('total_bank_rows', models.IntegerField(default=0)),
                ('total_gl_rows', models.IntegerField(default=0)),
                ('matched_count', models.IntegerField(default=0)),
                ('exception_count', models.IntegerField(default=0)),
                ('opening_balance', models.DecimalField(decimal_places=2, default=Decimal('184352.19'), max_digits=15)),
                ('bank_closing_balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('gl_closing_balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('adjusted_bank_balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('adjusted_gl_balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('unreconciled_difference', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('match_rate', models.FloatField(default=0.0)),
                ('timing_window_days', models.IntegerField(default=5)),
                ('tolerance_amount', models.DecimalField(decimal_places=2, default=Decimal('1.00'), max_digits=10)),
                ('fuzzy_threshold', models.FloatField(default=0.35)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reconciliation_batches', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DiscrepancyException',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('side', models.CharField(choices=[('BANK', 'Bank Side'), ('GL', 'Company/GL Side')], db_index=True, max_length=10)),
                ('category', models.CharField(choices=[('BANK_CHARGE', 'Bank Charge / Service Fee'), ('INTEREST', 'Interest Income / Expense'), ('NSF', 'NSF Returned Item'), ('UNIDENTIFIED_CREDIT', 'Unidentified Credit'), ('UNIDENTIFIED_DEBIT', 'Unidentified Debit'), ('OUTSTANDING_CHECK', 'Outstanding Check / Payment'), ('DEPOSIT_IN_TRANSIT', 'Deposit in Transit'), ('DUPLICATE_POSTING', 'Possible Duplicate Posting'), ('AMOUNT_MISMATCH', 'Amount Mismatch'), ('DATE_MISMATCH', 'Date Mismatch'), ('MISSING_TRANSACTION', 'Missing Transaction')], db_index=True, default='MISSING_TRANSACTION', max_length=50)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('reason', models.CharField(max_length=255)),
                ('suggested_action', models.TextField()),
                ('rank', models.IntegerField(default=1)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('RESOLVED', 'Resolved'), ('IGNORED', 'Ignored')], db_index=True, default='OPEN', max_length=20)),
                ('review_notes', models.TextField(blank=True, null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bank_tx', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exception_records', to='reconciliation.banktransaction')),
                ('company_tx', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exception_records', to='reconciliation.companytransaction')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_exceptions', to=settings.AUTH_USER_MODEL)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exceptions', to='reconciliation.reconciliationbatch')),
            ],
            options={
                'ordering': ['-amount', 'id'],
            },
        ),
        migrations.AddField(
            model_name='companytransaction',
            name='batch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_transactions', to='reconciliation.reconciliationbatch'),
        ),
        migrations.AddField(
            model_name='banktransaction',
            name='batch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bank_transactions', to='reconciliation.reconciliationbatch'),
        ),
        migrations.CreateModel(
            name='ReconciliationMatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pass_name', models.CharField(default='Exact', max_length=50)),
                ('confidence_score', models.FloatField(default=100.0)),
                ('amount_delta', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('date_delta', models.IntegerField(default=0)),
                ('fuzzy_score', models.FloatField(default=1.0)),
                ('status', models.CharField(choices=[('PENDING_REVIEW', 'Pending Review'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], db_index=True, default='APPROVED', max_length=20)),
                ('review_notes', models.TextField(blank=True, null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bank_tx', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matched_pair', to='reconciliation.banktransaction')),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='reconciliation.reconciliationbatch')),
                ('company_tx', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matched_pair', to='reconciliation.companytransaction')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_matches', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-confidence_score', 'id'],
            },
        ),
    ]
